name: Create Platform Wheels

on: [push]

jobs:
  manylinux-x86_64-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout pandas
      uses: actions/checkout@master
      with:
        repository: pandas-dev/pandas
    - name: Checkout release repo for build script
      uses: actions/checkout@master
      with:
        path: "pandas-release"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Docker Build
      run: |
        docker run --rm -e PLAT=manylinux1_x86_64 -e PYVER=${{ matrix.python-version }} -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/pandas-release/manylinux_build.sh
    - name: Install and test wheel
      run: |
        mkdir temp
        cd temp
        python -m pip install --upgrade pip
        python -m pip install pandas --no-index -f ../wheelhouse
        python -c "import pandas; pandas.test()"
        cd ..
    - name: Upload linux wheel artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.python-version }}-manylinux
        path: wheelhouse

  manylinux-i686-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout pandas
      uses: actions/checkout@master
      with:
        repository: pandas-dev/pandas
    - name: Checkout release repo for build script
      uses: actions/checkout@master
      with:
        path: "pandas-release"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Docker Build
      run: |
        docker run --rm -e PLAT=manylinux1_i686 -e PYVER=${{ matrix.python-version }} -v `pwd`:/io quay.io/pypa/manylinux1_i686 /io/pandas-release/manylinux_build.sh
    - name: Install and test wheel
      run: |
        mkdir temp
        cd temp
        python -m pip install --upgrade pip
        python -m pip install pandas --no-index -f ../wheelhouse
        python -c "import pandas; pandas.test()"
        cd ..
    - name: Upload linux wheel artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.python-version }}-manylinux
        path: wheelhouse

  macos-wheel:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout pandas
      uses: actions/checkout@master
      with:
        repository: pandas-dev/pandas
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel cython numpy python-dateutil pytz
    - name: Build wheels
      run: |
        python setup.py bdist_wheel
    - name: Install and test wheel
      run: |
        mkdir temp
        cd temp
        python -m pip install pytest
        python -m pip install pandas --no-index -f ../dist
        python -c "import pandas; pandas.test()"
        cd ..
    - name: Upload linux wheel artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.python-version }}-macos
        path: dist

  windows-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout pandas
      uses: actions/checkout@master
      with:
        repository: pandas-dev/pandas
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel cython numpy python-dateutil pytz
    - name: Build wheels
      run: |
        python setup.py bdist_wheel
    - name: Install and test wheel
      run: |
        mkdir temp
        cd temp
        python -m pip install pytest
        python -m pip install pandas --no-index -f ../dist
        python -c "import pandas; pandas.test()"
        cd ..
    - name: Upload linux wheel artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.python-version }}-macos
        path: dist